# Generated by Django 3.0 on 2020-03-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200320_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcomment',
            old_name='postSlug',
            new_name='postId',
        ),
    ]
