# Generated by Django 3.0 on 2020-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200320_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcomment',
            name='commentId',
        ),
        migrations.AddField(
            model_name='blogpostcomment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
