# Generated by Django 3.0 on 2020-03-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200320_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcomment',
            old_name='postId',
            new_name='post',
        ),
    ]
