# Generated by Django 3.0 on 2020-03-21 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200320_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.BlogPost'),
        ),
    ]
